### ISSUE TITLE
As a coach i want to add players into a team

### ISSUE THREAD

**Issue by alejandrovillegas** [teamaidapp/aid_app#5]
As a coach, i want to add players to a team

acceptance criteria

- Add player view
- Search player View
- Autocomplete on search. 

![image](https://github.com/teamaidapp/aid_app/assets/3981512/5d38489e-87df-4fca-a0cc-4ca48c485664)

**Comment by juanesteban1403** [comment]
back -> Done

**Comment by luis-cruzt** [comment]
Normal search - Done
![image](https://github.com/teamaidapp/aid_app/assets/55716036/9fa35735-f944-4204-91e0-a84053904e61)

Advanced Search - Done
Some tests where done, we need more tests
![image](https://github.com/teamaidapp/aid_app/assets/55716036/b16dd7a0-c515-4d5a-81c7-c669f289932a)

**Comment by luis-cruzt** [comment]
If there are any new bugs, let's open new issues 👍🏻
