### ISSUE TITLE
As a team member i want to check the user list

### ISSUE THREAD

**Issue by alejandrovillegas** [teamaidapp/aid_app#6]
As a team member, I want to check the user list

**Acceptance criteria**

- Contact List team view
- list of users. 
- phone call action. 
- search users

![image](https://github.com/teamaidapp/aid_app/assets/3981512/b88332fb-2746-4f33-a253-f160bf32bb2a)

**Comment by juanesteban1403** [comment]
back-> Done

**Comment by luis-cruzt** [comment]
front -> done
