### ISSUE TITLE
As a coach i want to create a schedule

### ISSUE THREAD

**Issue by alejandrovillegas** [teamaidapp/aid_app#7]
### As a coach, I want to create a schedule

**acepteance criteria** 

- schedule view
- location with autocomplete 
- guest with autocomplete. 

NOTE
add a notes fields [a text field not requited in the form]

![image](https://github.com/teamaidapp/aid_app/assets/3981512/8c2fde5d-7c6b-491f-bd0d-c59aa13c362e)

**Comment by juanesteban1403** [comment]
back-> Done
