### ISSUE TITLE
As a team member i want to create a travel

### ISSUE THREAD

**Issue by teamaidapp** [teamaidapp/aid_app#8]
As a coach, i want to create a travel

**Acceptance criteria.** 
Travel is associated with a team

**Note**
Add a notes field in a travel status
Remember I can add different types of travel. 
![image](https://github.com/teamaidapp/aid_app/assets/3981512/0cfec1a7-d295-4684-a823-78d873203c7a)

![image](https://github.com/teamaidapp/aid_app/assets/3981512/17710644-b5ce-4755-9a07-1f77d0ea3ba5)

**Comment by juanesteban1403** [comment]
Back-> Done
